//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_ventas
    {
        public int Id { get; set; }
        public string cantidad { get; set; }
        public int ArticulosId { get; set; }
        public int VentasId { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
